modLoader="javafml"
loaderVersion="[47,)"
license="none"

[[mods]]
modId="innofixes"
version="1.0.0"
displayName="innofixes"
authors="baffledhedgehog"
description='''i love crashing'''

[[dependencies.innofixes]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.innofixes]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"
