modLoader="javafml"
loaderVersion="[47,)"
license="none"

[[mods]]
modId="innofixes"
version="${file.jarVersion}"
displayName="InnoFixes"
authors="baffledhedgehog"
description='''Моё тело это машина превращающая баги в ещё больше багов'''

[[dependencies.innofixes]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.innofixes]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.innofixes]]
modId="artifacts"
mandatory=true
versionRange="[9.5.16,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="relics"
mandatory=true
versionRange="[0.8.0.11,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="attributeslib"
mandatory=true
versionRange="[1.3.7,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="apotheosis"
mandatory=true
versionRange="[7.4.8,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="create"
mandatory=true
versionRange="[6.0.8,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="createpropulsion"
mandatory=true
versionRange="[0.3.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="create_blaze_burner_fuels"
mandatory=true
versionRange="[1.0.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="create_connected"
mandatory=true
versionRange="[1.1.10-mc1.20.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="create_tweaked_controllers"
mandatory=true
versionRange="[1.20.1-1.2.5,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="create_ultimate_factory"
mandatory=true
versionRange="[2.2.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="mna"
mandatory=true
versionRange="[3.1.11,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="innoadditions"
mandatory=false
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="mna_attrib_apoth"
mandatory=true
versionRange="[0.5-1.20.1,)"
ordering="AFTER"
side="BOTH"
